# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.16

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /home/chasar/.local/share/JetBrains/Toolbox/apps/CLion/ch-0/201.7846.88/bin/cmake/linux/bin/cmake

# The command to remove a file.
RM = /home/chasar/.local/share/JetBrains/Toolbox/apps/CLion/ch-0/201.7846.88/bin/cmake/linux/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/chasar/CLionProjects/display

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/chasar/CLionProjects/display

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/home/chasar/.local/share/JetBrains/Toolbox/apps/CLion/ch-0/201.7846.88/bin/cmake/linux/bin/cmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/home/chasar/.local/share/JetBrains/Toolbox/apps/CLion/ch-0/201.7846.88/bin/cmake/linux/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/chasar/CLionProjects/display/CMakeFiles /home/chasar/CLionProjects/display/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/chasar/CLionProjects/display/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named Production

# Build rule for target.
Production: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 Production
.PHONY : Production

# fast build rule for target.
Production/fast:
	$(MAKE) -f CMakeFiles/Production.dir/build.make CMakeFiles/Production.dir/build
.PHONY : Production/fast

#=============================================================================
# Target rules for targets named Debug

# Build rule for target.
Debug: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 Debug
.PHONY : Debug

# fast build rule for target.
Debug/fast:
	$(MAKE) -f CMakeFiles/Debug.dir/build.make CMakeFiles/Debug.dir/build
.PHONY : Debug/fast

#=============================================================================
# Target rules for targets named Z_DUMMY_TARGET

# Build rule for target.
Z_DUMMY_TARGET: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 Z_DUMMY_TARGET
.PHONY : Z_DUMMY_TARGET

# fast build rule for target.
Z_DUMMY_TARGET/fast:
	$(MAKE) -f CMakeFiles/Z_DUMMY_TARGET.dir/build.make CMakeFiles/Z_DUMMY_TARGET.dir/build
.PHONY : Z_DUMMY_TARGET/fast

.pio/libdeps/featheresp32/Adafruit_BusIO_ID6214/Adafruit_BusIO_Register.obj: .pio/libdeps/featheresp32/Adafruit_BusIO_ID6214/Adafruit_BusIO_Register.cpp.obj

.PHONY : .pio/libdeps/featheresp32/Adafruit_BusIO_ID6214/Adafruit_BusIO_Register.obj

# target to build an object file
.pio/libdeps/featheresp32/Adafruit_BusIO_ID6214/Adafruit_BusIO_Register.cpp.obj:
	$(MAKE) -f CMakeFiles/Z_DUMMY_TARGET.dir/build.make CMakeFiles/Z_DUMMY_TARGET.dir/.pio/libdeps/featheresp32/Adafruit_BusIO_ID6214/Adafruit_BusIO_Register.cpp.obj
.PHONY : .pio/libdeps/featheresp32/Adafruit_BusIO_ID6214/Adafruit_BusIO_Register.cpp.obj

.pio/libdeps/featheresp32/Adafruit_BusIO_ID6214/Adafruit_BusIO_Register.i: .pio/libdeps/featheresp32/Adafruit_BusIO_ID6214/Adafruit_BusIO_Register.cpp.i

.PHONY : .pio/libdeps/featheresp32/Adafruit_BusIO_ID6214/Adafruit_BusIO_Register.i

# target to preprocess a source file
.pio/libdeps/featheresp32/Adafruit_BusIO_ID6214/Adafruit_BusIO_Register.cpp.i:
	$(MAKE) -f CMakeFiles/Z_DUMMY_TARGET.dir/build.make CMakeFiles/Z_DUMMY_TARGET.dir/.pio/libdeps/featheresp32/Adafruit_BusIO_ID6214/Adafruit_BusIO_Register.cpp.i
.PHONY : .pio/libdeps/featheresp32/Adafruit_BusIO_ID6214/Adafruit_BusIO_Register.cpp.i

.pio/libdeps/featheresp32/Adafruit_BusIO_ID6214/Adafruit_BusIO_Register.s: .pio/libdeps/featheresp32/Adafruit_BusIO_ID6214/Adafruit_BusIO_Register.cpp.s

.PHONY : .pio/libdeps/featheresp32/Adafruit_BusIO_ID6214/Adafruit_BusIO_Register.s

# target to generate assembly for a file
.pio/libdeps/featheresp32/Adafruit_BusIO_ID6214/Adafruit_BusIO_Register.cpp.s:
	$(MAKE) -f CMakeFiles/Z_DUMMY_TARGET.dir/build.make CMakeFiles/Z_DUMMY_TARGET.dir/.pio/libdeps/featheresp32/Adafruit_BusIO_ID6214/Adafruit_BusIO_Register.cpp.s
.PHONY : .pio/libdeps/featheresp32/Adafruit_BusIO_ID6214/Adafruit_BusIO_Register.cpp.s

.pio/libdeps/featheresp32/Adafruit_BusIO_ID6214/Adafruit_I2CDevice.obj: .pio/libdeps/featheresp32/Adafruit_BusIO_ID6214/Adafruit_I2CDevice.cpp.obj

.PHONY : .pio/libdeps/featheresp32/Adafruit_BusIO_ID6214/Adafruit_I2CDevice.obj

# target to build an object file
.pio/libdeps/featheresp32/Adafruit_BusIO_ID6214/Adafruit_I2CDevice.cpp.obj:
	$(MAKE) -f CMakeFiles/Z_DUMMY_TARGET.dir/build.make CMakeFiles/Z_DUMMY_TARGET.dir/.pio/libdeps/featheresp32/Adafruit_BusIO_ID6214/Adafruit_I2CDevice.cpp.obj
.PHONY : .pio/libdeps/featheresp32/Adafruit_BusIO_ID6214/Adafruit_I2CDevice.cpp.obj

.pio/libdeps/featheresp32/Adafruit_BusIO_ID6214/Adafruit_I2CDevice.i: .pio/libdeps/featheresp32/Adafruit_BusIO_ID6214/Adafruit_I2CDevice.cpp.i

.PHONY : .pio/libdeps/featheresp32/Adafruit_BusIO_ID6214/Adafruit_I2CDevice.i

# target to preprocess a source file
.pio/libdeps/featheresp32/Adafruit_BusIO_ID6214/Adafruit_I2CDevice.cpp.i:
	$(MAKE) -f CMakeFiles/Z_DUMMY_TARGET.dir/build.make CMakeFiles/Z_DUMMY_TARGET.dir/.pio/libdeps/featheresp32/Adafruit_BusIO_ID6214/Adafruit_I2CDevice.cpp.i
.PHONY : .pio/libdeps/featheresp32/Adafruit_BusIO_ID6214/Adafruit_I2CDevice.cpp.i

.pio/libdeps/featheresp32/Adafruit_BusIO_ID6214/Adafruit_I2CDevice.s: .pio/libdeps/featheresp32/Adafruit_BusIO_ID6214/Adafruit_I2CDevice.cpp.s

.PHONY : .pio/libdeps/featheresp32/Adafruit_BusIO_ID6214/Adafruit_I2CDevice.s

# target to generate assembly for a file
.pio/libdeps/featheresp32/Adafruit_BusIO_ID6214/Adafruit_I2CDevice.cpp.s:
	$(MAKE) -f CMakeFiles/Z_DUMMY_TARGET.dir/build.make CMakeFiles/Z_DUMMY_TARGET.dir/.pio/libdeps/featheresp32/Adafruit_BusIO_ID6214/Adafruit_I2CDevice.cpp.s
.PHONY : .pio/libdeps/featheresp32/Adafruit_BusIO_ID6214/Adafruit_I2CDevice.cpp.s

.pio/libdeps/featheresp32/Adafruit_BusIO_ID6214/Adafruit_SPIDevice.obj: .pio/libdeps/featheresp32/Adafruit_BusIO_ID6214/Adafruit_SPIDevice.cpp.obj

.PHONY : .pio/libdeps/featheresp32/Adafruit_BusIO_ID6214/Adafruit_SPIDevice.obj

# target to build an object file
.pio/libdeps/featheresp32/Adafruit_BusIO_ID6214/Adafruit_SPIDevice.cpp.obj:
	$(MAKE) -f CMakeFiles/Z_DUMMY_TARGET.dir/build.make CMakeFiles/Z_DUMMY_TARGET.dir/.pio/libdeps/featheresp32/Adafruit_BusIO_ID6214/Adafruit_SPIDevice.cpp.obj
.PHONY : .pio/libdeps/featheresp32/Adafruit_BusIO_ID6214/Adafruit_SPIDevice.cpp.obj

.pio/libdeps/featheresp32/Adafruit_BusIO_ID6214/Adafruit_SPIDevice.i: .pio/libdeps/featheresp32/Adafruit_BusIO_ID6214/Adafruit_SPIDevice.cpp.i

.PHONY : .pio/libdeps/featheresp32/Adafruit_BusIO_ID6214/Adafruit_SPIDevice.i

# target to preprocess a source file
.pio/libdeps/featheresp32/Adafruit_BusIO_ID6214/Adafruit_SPIDevice.cpp.i:
	$(MAKE) -f CMakeFiles/Z_DUMMY_TARGET.dir/build.make CMakeFiles/Z_DUMMY_TARGET.dir/.pio/libdeps/featheresp32/Adafruit_BusIO_ID6214/Adafruit_SPIDevice.cpp.i
.PHONY : .pio/libdeps/featheresp32/Adafruit_BusIO_ID6214/Adafruit_SPIDevice.cpp.i

.pio/libdeps/featheresp32/Adafruit_BusIO_ID6214/Adafruit_SPIDevice.s: .pio/libdeps/featheresp32/Adafruit_BusIO_ID6214/Adafruit_SPIDevice.cpp.s

.PHONY : .pio/libdeps/featheresp32/Adafruit_BusIO_ID6214/Adafruit_SPIDevice.s

# target to generate assembly for a file
.pio/libdeps/featheresp32/Adafruit_BusIO_ID6214/Adafruit_SPIDevice.cpp.s:
	$(MAKE) -f CMakeFiles/Z_DUMMY_TARGET.dir/build.make CMakeFiles/Z_DUMMY_TARGET.dir/.pio/libdeps/featheresp32/Adafruit_BusIO_ID6214/Adafruit_SPIDevice.cpp.s
.PHONY : .pio/libdeps/featheresp32/Adafruit_BusIO_ID6214/Adafruit_SPIDevice.cpp.s

.pio/libdeps/featheresp32/Adafruit_GFX_Library_ID13/Adafruit_GFX.obj: .pio/libdeps/featheresp32/Adafruit_GFX_Library_ID13/Adafruit_GFX.cpp.obj

.PHONY : .pio/libdeps/featheresp32/Adafruit_GFX_Library_ID13/Adafruit_GFX.obj

# target to build an object file
.pio/libdeps/featheresp32/Adafruit_GFX_Library_ID13/Adafruit_GFX.cpp.obj:
	$(MAKE) -f CMakeFiles/Z_DUMMY_TARGET.dir/build.make CMakeFiles/Z_DUMMY_TARGET.dir/.pio/libdeps/featheresp32/Adafruit_GFX_Library_ID13/Adafruit_GFX.cpp.obj
.PHONY : .pio/libdeps/featheresp32/Adafruit_GFX_Library_ID13/Adafruit_GFX.cpp.obj

.pio/libdeps/featheresp32/Adafruit_GFX_Library_ID13/Adafruit_GFX.i: .pio/libdeps/featheresp32/Adafruit_GFX_Library_ID13/Adafruit_GFX.cpp.i

.PHONY : .pio/libdeps/featheresp32/Adafruit_GFX_Library_ID13/Adafruit_GFX.i

# target to preprocess a source file
.pio/libdeps/featheresp32/Adafruit_GFX_Library_ID13/Adafruit_GFX.cpp.i:
	$(MAKE) -f CMakeFiles/Z_DUMMY_TARGET.dir/build.make CMakeFiles/Z_DUMMY_TARGET.dir/.pio/libdeps/featheresp32/Adafruit_GFX_Library_ID13/Adafruit_GFX.cpp.i
.PHONY : .pio/libdeps/featheresp32/Adafruit_GFX_Library_ID13/Adafruit_GFX.cpp.i

.pio/libdeps/featheresp32/Adafruit_GFX_Library_ID13/Adafruit_GFX.s: .pio/libdeps/featheresp32/Adafruit_GFX_Library_ID13/Adafruit_GFX.cpp.s

.PHONY : .pio/libdeps/featheresp32/Adafruit_GFX_Library_ID13/Adafruit_GFX.s

# target to generate assembly for a file
.pio/libdeps/featheresp32/Adafruit_GFX_Library_ID13/Adafruit_GFX.cpp.s:
	$(MAKE) -f CMakeFiles/Z_DUMMY_TARGET.dir/build.make CMakeFiles/Z_DUMMY_TARGET.dir/.pio/libdeps/featheresp32/Adafruit_GFX_Library_ID13/Adafruit_GFX.cpp.s
.PHONY : .pio/libdeps/featheresp32/Adafruit_GFX_Library_ID13/Adafruit_GFX.cpp.s

.pio/libdeps/featheresp32/Adafruit_GFX_Library_ID13/Adafruit_MonoOLED.obj: .pio/libdeps/featheresp32/Adafruit_GFX_Library_ID13/Adafruit_MonoOLED.cpp.obj

.PHONY : .pio/libdeps/featheresp32/Adafruit_GFX_Library_ID13/Adafruit_MonoOLED.obj

# target to build an object file
.pio/libdeps/featheresp32/Adafruit_GFX_Library_ID13/Adafruit_MonoOLED.cpp.obj:
	$(MAKE) -f CMakeFiles/Z_DUMMY_TARGET.dir/build.make CMakeFiles/Z_DUMMY_TARGET.dir/.pio/libdeps/featheresp32/Adafruit_GFX_Library_ID13/Adafruit_MonoOLED.cpp.obj
.PHONY : .pio/libdeps/featheresp32/Adafruit_GFX_Library_ID13/Adafruit_MonoOLED.cpp.obj

.pio/libdeps/featheresp32/Adafruit_GFX_Library_ID13/Adafruit_MonoOLED.i: .pio/libdeps/featheresp32/Adafruit_GFX_Library_ID13/Adafruit_MonoOLED.cpp.i

.PHONY : .pio/libdeps/featheresp32/Adafruit_GFX_Library_ID13/Adafruit_MonoOLED.i

# target to preprocess a source file
.pio/libdeps/featheresp32/Adafruit_GFX_Library_ID13/Adafruit_MonoOLED.cpp.i:
	$(MAKE) -f CMakeFiles/Z_DUMMY_TARGET.dir/build.make CMakeFiles/Z_DUMMY_TARGET.dir/.pio/libdeps/featheresp32/Adafruit_GFX_Library_ID13/Adafruit_MonoOLED.cpp.i
.PHONY : .pio/libdeps/featheresp32/Adafruit_GFX_Library_ID13/Adafruit_MonoOLED.cpp.i

.pio/libdeps/featheresp32/Adafruit_GFX_Library_ID13/Adafruit_MonoOLED.s: .pio/libdeps/featheresp32/Adafruit_GFX_Library_ID13/Adafruit_MonoOLED.cpp.s

.PHONY : .pio/libdeps/featheresp32/Adafruit_GFX_Library_ID13/Adafruit_MonoOLED.s

# target to generate assembly for a file
.pio/libdeps/featheresp32/Adafruit_GFX_Library_ID13/Adafruit_MonoOLED.cpp.s:
	$(MAKE) -f CMakeFiles/Z_DUMMY_TARGET.dir/build.make CMakeFiles/Z_DUMMY_TARGET.dir/.pio/libdeps/featheresp32/Adafruit_GFX_Library_ID13/Adafruit_MonoOLED.cpp.s
.PHONY : .pio/libdeps/featheresp32/Adafruit_GFX_Library_ID13/Adafruit_MonoOLED.cpp.s

.pio/libdeps/featheresp32/Adafruit_GFX_Library_ID13/Adafruit_SPITFT.obj: .pio/libdeps/featheresp32/Adafruit_GFX_Library_ID13/Adafruit_SPITFT.cpp.obj

.PHONY : .pio/libdeps/featheresp32/Adafruit_GFX_Library_ID13/Adafruit_SPITFT.obj

# target to build an object file
.pio/libdeps/featheresp32/Adafruit_GFX_Library_ID13/Adafruit_SPITFT.cpp.obj:
	$(MAKE) -f CMakeFiles/Z_DUMMY_TARGET.dir/build.make CMakeFiles/Z_DUMMY_TARGET.dir/.pio/libdeps/featheresp32/Adafruit_GFX_Library_ID13/Adafruit_SPITFT.cpp.obj
.PHONY : .pio/libdeps/featheresp32/Adafruit_GFX_Library_ID13/Adafruit_SPITFT.cpp.obj

.pio/libdeps/featheresp32/Adafruit_GFX_Library_ID13/Adafruit_SPITFT.i: .pio/libdeps/featheresp32/Adafruit_GFX_Library_ID13/Adafruit_SPITFT.cpp.i

.PHONY : .pio/libdeps/featheresp32/Adafruit_GFX_Library_ID13/Adafruit_SPITFT.i

# target to preprocess a source file
.pio/libdeps/featheresp32/Adafruit_GFX_Library_ID13/Adafruit_SPITFT.cpp.i:
	$(MAKE) -f CMakeFiles/Z_DUMMY_TARGET.dir/build.make CMakeFiles/Z_DUMMY_TARGET.dir/.pio/libdeps/featheresp32/Adafruit_GFX_Library_ID13/Adafruit_SPITFT.cpp.i
.PHONY : .pio/libdeps/featheresp32/Adafruit_GFX_Library_ID13/Adafruit_SPITFT.cpp.i

.pio/libdeps/featheresp32/Adafruit_GFX_Library_ID13/Adafruit_SPITFT.s: .pio/libdeps/featheresp32/Adafruit_GFX_Library_ID13/Adafruit_SPITFT.cpp.s

.PHONY : .pio/libdeps/featheresp32/Adafruit_GFX_Library_ID13/Adafruit_SPITFT.s

# target to generate assembly for a file
.pio/libdeps/featheresp32/Adafruit_GFX_Library_ID13/Adafruit_SPITFT.cpp.s:
	$(MAKE) -f CMakeFiles/Z_DUMMY_TARGET.dir/build.make CMakeFiles/Z_DUMMY_TARGET.dir/.pio/libdeps/featheresp32/Adafruit_GFX_Library_ID13/Adafruit_SPITFT.cpp.s
.PHONY : .pio/libdeps/featheresp32/Adafruit_GFX_Library_ID13/Adafruit_SPITFT.cpp.s

.pio/libdeps/featheresp32/Adafruit_GFX_Library_ID13/examples/GFXcanvas/GFXcanvasSerialDemo.obj: .pio/libdeps/featheresp32/Adafruit_GFX_Library_ID13/examples/GFXcanvas/GFXcanvasSerialDemo.cpp.obj

.PHONY : .pio/libdeps/featheresp32/Adafruit_GFX_Library_ID13/examples/GFXcanvas/GFXcanvasSerialDemo.obj

# target to build an object file
.pio/libdeps/featheresp32/Adafruit_GFX_Library_ID13/examples/GFXcanvas/GFXcanvasSerialDemo.cpp.obj:
	$(MAKE) -f CMakeFiles/Z_DUMMY_TARGET.dir/build.make CMakeFiles/Z_DUMMY_TARGET.dir/.pio/libdeps/featheresp32/Adafruit_GFX_Library_ID13/examples/GFXcanvas/GFXcanvasSerialDemo.cpp.obj
.PHONY : .pio/libdeps/featheresp32/Adafruit_GFX_Library_ID13/examples/GFXcanvas/GFXcanvasSerialDemo.cpp.obj

.pio/libdeps/featheresp32/Adafruit_GFX_Library_ID13/examples/GFXcanvas/GFXcanvasSerialDemo.i: .pio/libdeps/featheresp32/Adafruit_GFX_Library_ID13/examples/GFXcanvas/GFXcanvasSerialDemo.cpp.i

.PHONY : .pio/libdeps/featheresp32/Adafruit_GFX_Library_ID13/examples/GFXcanvas/GFXcanvasSerialDemo.i

# target to preprocess a source file
.pio/libdeps/featheresp32/Adafruit_GFX_Library_ID13/examples/GFXcanvas/GFXcanvasSerialDemo.cpp.i:
	$(MAKE) -f CMakeFiles/Z_DUMMY_TARGET.dir/build.make CMakeFiles/Z_DUMMY_TARGET.dir/.pio/libdeps/featheresp32/Adafruit_GFX_Library_ID13/examples/GFXcanvas/GFXcanvasSerialDemo.cpp.i
.PHONY : .pio/libdeps/featheresp32/Adafruit_GFX_Library_ID13/examples/GFXcanvas/GFXcanvasSerialDemo.cpp.i

.pio/libdeps/featheresp32/Adafruit_GFX_Library_ID13/examples/GFXcanvas/GFXcanvasSerialDemo.s: .pio/libdeps/featheresp32/Adafruit_GFX_Library_ID13/examples/GFXcanvas/GFXcanvasSerialDemo.cpp.s

.PHONY : .pio/libdeps/featheresp32/Adafruit_GFX_Library_ID13/examples/GFXcanvas/GFXcanvasSerialDemo.s

# target to generate assembly for a file
.pio/libdeps/featheresp32/Adafruit_GFX_Library_ID13/examples/GFXcanvas/GFXcanvasSerialDemo.cpp.s:
	$(MAKE) -f CMakeFiles/Z_DUMMY_TARGET.dir/build.make CMakeFiles/Z_DUMMY_TARGET.dir/.pio/libdeps/featheresp32/Adafruit_GFX_Library_ID13/examples/GFXcanvas/GFXcanvasSerialDemo.cpp.s
.PHONY : .pio/libdeps/featheresp32/Adafruit_GFX_Library_ID13/examples/GFXcanvas/GFXcanvasSerialDemo.cpp.s

.pio/libdeps/featheresp32/Adafruit_GFX_Library_ID13/fontconvert/fontconvert.obj: .pio/libdeps/featheresp32/Adafruit_GFX_Library_ID13/fontconvert/fontconvert.c.obj

.PHONY : .pio/libdeps/featheresp32/Adafruit_GFX_Library_ID13/fontconvert/fontconvert.obj

# target to build an object file
.pio/libdeps/featheresp32/Adafruit_GFX_Library_ID13/fontconvert/fontconvert.c.obj:
	$(MAKE) -f CMakeFiles/Z_DUMMY_TARGET.dir/build.make CMakeFiles/Z_DUMMY_TARGET.dir/.pio/libdeps/featheresp32/Adafruit_GFX_Library_ID13/fontconvert/fontconvert.c.obj
.PHONY : .pio/libdeps/featheresp32/Adafruit_GFX_Library_ID13/fontconvert/fontconvert.c.obj

.pio/libdeps/featheresp32/Adafruit_GFX_Library_ID13/fontconvert/fontconvert.i: .pio/libdeps/featheresp32/Adafruit_GFX_Library_ID13/fontconvert/fontconvert.c.i

.PHONY : .pio/libdeps/featheresp32/Adafruit_GFX_Library_ID13/fontconvert/fontconvert.i

# target to preprocess a source file
.pio/libdeps/featheresp32/Adafruit_GFX_Library_ID13/fontconvert/fontconvert.c.i:
	$(MAKE) -f CMakeFiles/Z_DUMMY_TARGET.dir/build.make CMakeFiles/Z_DUMMY_TARGET.dir/.pio/libdeps/featheresp32/Adafruit_GFX_Library_ID13/fontconvert/fontconvert.c.i
.PHONY : .pio/libdeps/featheresp32/Adafruit_GFX_Library_ID13/fontconvert/fontconvert.c.i

.pio/libdeps/featheresp32/Adafruit_GFX_Library_ID13/fontconvert/fontconvert.s: .pio/libdeps/featheresp32/Adafruit_GFX_Library_ID13/fontconvert/fontconvert.c.s

.PHONY : .pio/libdeps/featheresp32/Adafruit_GFX_Library_ID13/fontconvert/fontconvert.s

# target to generate assembly for a file
.pio/libdeps/featheresp32/Adafruit_GFX_Library_ID13/fontconvert/fontconvert.c.s:
	$(MAKE) -f CMakeFiles/Z_DUMMY_TARGET.dir/build.make CMakeFiles/Z_DUMMY_TARGET.dir/.pio/libdeps/featheresp32/Adafruit_GFX_Library_ID13/fontconvert/fontconvert.c.s
.PHONY : .pio/libdeps/featheresp32/Adafruit_GFX_Library_ID13/fontconvert/fontconvert.c.s

.pio/libdeps/featheresp32/Adafruit_GFX_Library_ID13/glcdfont.obj: .pio/libdeps/featheresp32/Adafruit_GFX_Library_ID13/glcdfont.c.obj

.PHONY : .pio/libdeps/featheresp32/Adafruit_GFX_Library_ID13/glcdfont.obj

# target to build an object file
.pio/libdeps/featheresp32/Adafruit_GFX_Library_ID13/glcdfont.c.obj:
	$(MAKE) -f CMakeFiles/Z_DUMMY_TARGET.dir/build.make CMakeFiles/Z_DUMMY_TARGET.dir/.pio/libdeps/featheresp32/Adafruit_GFX_Library_ID13/glcdfont.c.obj
.PHONY : .pio/libdeps/featheresp32/Adafruit_GFX_Library_ID13/glcdfont.c.obj

.pio/libdeps/featheresp32/Adafruit_GFX_Library_ID13/glcdfont.i: .pio/libdeps/featheresp32/Adafruit_GFX_Library_ID13/glcdfont.c.i

.PHONY : .pio/libdeps/featheresp32/Adafruit_GFX_Library_ID13/glcdfont.i

# target to preprocess a source file
.pio/libdeps/featheresp32/Adafruit_GFX_Library_ID13/glcdfont.c.i:
	$(MAKE) -f CMakeFiles/Z_DUMMY_TARGET.dir/build.make CMakeFiles/Z_DUMMY_TARGET.dir/.pio/libdeps/featheresp32/Adafruit_GFX_Library_ID13/glcdfont.c.i
.PHONY : .pio/libdeps/featheresp32/Adafruit_GFX_Library_ID13/glcdfont.c.i

.pio/libdeps/featheresp32/Adafruit_GFX_Library_ID13/glcdfont.s: .pio/libdeps/featheresp32/Adafruit_GFX_Library_ID13/glcdfont.c.s

.PHONY : .pio/libdeps/featheresp32/Adafruit_GFX_Library_ID13/glcdfont.s

# target to generate assembly for a file
.pio/libdeps/featheresp32/Adafruit_GFX_Library_ID13/glcdfont.c.s:
	$(MAKE) -f CMakeFiles/Z_DUMMY_TARGET.dir/build.make CMakeFiles/Z_DUMMY_TARGET.dir/.pio/libdeps/featheresp32/Adafruit_GFX_Library_ID13/glcdfont.c.s
.PHONY : .pio/libdeps/featheresp32/Adafruit_GFX_Library_ID13/glcdfont.c.s

.pio/libdeps/featheresp32/ESPRandom_ID6883/ESPRandom.obj: .pio/libdeps/featheresp32/ESPRandom_ID6883/ESPRandom.cpp.obj

.PHONY : .pio/libdeps/featheresp32/ESPRandom_ID6883/ESPRandom.obj

# target to build an object file
.pio/libdeps/featheresp32/ESPRandom_ID6883/ESPRandom.cpp.obj:
	$(MAKE) -f CMakeFiles/Z_DUMMY_TARGET.dir/build.make CMakeFiles/Z_DUMMY_TARGET.dir/.pio/libdeps/featheresp32/ESPRandom_ID6883/ESPRandom.cpp.obj
.PHONY : .pio/libdeps/featheresp32/ESPRandom_ID6883/ESPRandom.cpp.obj

.pio/libdeps/featheresp32/ESPRandom_ID6883/ESPRandom.i: .pio/libdeps/featheresp32/ESPRandom_ID6883/ESPRandom.cpp.i

.PHONY : .pio/libdeps/featheresp32/ESPRandom_ID6883/ESPRandom.i

# target to preprocess a source file
.pio/libdeps/featheresp32/ESPRandom_ID6883/ESPRandom.cpp.i:
	$(MAKE) -f CMakeFiles/Z_DUMMY_TARGET.dir/build.make CMakeFiles/Z_DUMMY_TARGET.dir/.pio/libdeps/featheresp32/ESPRandom_ID6883/ESPRandom.cpp.i
.PHONY : .pio/libdeps/featheresp32/ESPRandom_ID6883/ESPRandom.cpp.i

.pio/libdeps/featheresp32/ESPRandom_ID6883/ESPRandom.s: .pio/libdeps/featheresp32/ESPRandom_ID6883/ESPRandom.cpp.s

.PHONY : .pio/libdeps/featheresp32/ESPRandom_ID6883/ESPRandom.s

# target to generate assembly for a file
.pio/libdeps/featheresp32/ESPRandom_ID6883/ESPRandom.cpp.s:
	$(MAKE) -f CMakeFiles/Z_DUMMY_TARGET.dir/build.make CMakeFiles/Z_DUMMY_TARGET.dir/.pio/libdeps/featheresp32/ESPRandom_ID6883/ESPRandom.cpp.s
.PHONY : .pio/libdeps/featheresp32/ESPRandom_ID6883/ESPRandom.cpp.s

.pio/libdeps/featheresp32/ESPRandom_ID6883/examples/get_random_number.obj: .pio/libdeps/featheresp32/ESPRandom_ID6883/examples/get_random_number.cpp.obj

.PHONY : .pio/libdeps/featheresp32/ESPRandom_ID6883/examples/get_random_number.obj

# target to build an object file
.pio/libdeps/featheresp32/ESPRandom_ID6883/examples/get_random_number.cpp.obj:
	$(MAKE) -f CMakeFiles/Z_DUMMY_TARGET.dir/build.make CMakeFiles/Z_DUMMY_TARGET.dir/.pio/libdeps/featheresp32/ESPRandom_ID6883/examples/get_random_number.cpp.obj
.PHONY : .pio/libdeps/featheresp32/ESPRandom_ID6883/examples/get_random_number.cpp.obj

.pio/libdeps/featheresp32/ESPRandom_ID6883/examples/get_random_number.i: .pio/libdeps/featheresp32/ESPRandom_ID6883/examples/get_random_number.cpp.i

.PHONY : .pio/libdeps/featheresp32/ESPRandom_ID6883/examples/get_random_number.i

# target to preprocess a source file
.pio/libdeps/featheresp32/ESPRandom_ID6883/examples/get_random_number.cpp.i:
	$(MAKE) -f CMakeFiles/Z_DUMMY_TARGET.dir/build.make CMakeFiles/Z_DUMMY_TARGET.dir/.pio/libdeps/featheresp32/ESPRandom_ID6883/examples/get_random_number.cpp.i
.PHONY : .pio/libdeps/featheresp32/ESPRandom_ID6883/examples/get_random_number.cpp.i

.pio/libdeps/featheresp32/ESPRandom_ID6883/examples/get_random_number.s: .pio/libdeps/featheresp32/ESPRandom_ID6883/examples/get_random_number.cpp.s

.PHONY : .pio/libdeps/featheresp32/ESPRandom_ID6883/examples/get_random_number.s

# target to generate assembly for a file
.pio/libdeps/featheresp32/ESPRandom_ID6883/examples/get_random_number.cpp.s:
	$(MAKE) -f CMakeFiles/Z_DUMMY_TARGET.dir/build.make CMakeFiles/Z_DUMMY_TARGET.dir/.pio/libdeps/featheresp32/ESPRandom_ID6883/examples/get_random_number.cpp.s
.PHONY : .pio/libdeps/featheresp32/ESPRandom_ID6883/examples/get_random_number.cpp.s

.pio/libdeps/featheresp32/ESPRandom_ID6883/examples/get_uuid.obj: .pio/libdeps/featheresp32/ESPRandom_ID6883/examples/get_uuid.cpp.obj

.PHONY : .pio/libdeps/featheresp32/ESPRandom_ID6883/examples/get_uuid.obj

# target to build an object file
.pio/libdeps/featheresp32/ESPRandom_ID6883/examples/get_uuid.cpp.obj:
	$(MAKE) -f CMakeFiles/Z_DUMMY_TARGET.dir/build.make CMakeFiles/Z_DUMMY_TARGET.dir/.pio/libdeps/featheresp32/ESPRandom_ID6883/examples/get_uuid.cpp.obj
.PHONY : .pio/libdeps/featheresp32/ESPRandom_ID6883/examples/get_uuid.cpp.obj

.pio/libdeps/featheresp32/ESPRandom_ID6883/examples/get_uuid.i: .pio/libdeps/featheresp32/ESPRandom_ID6883/examples/get_uuid.cpp.i

.PHONY : .pio/libdeps/featheresp32/ESPRandom_ID6883/examples/get_uuid.i

# target to preprocess a source file
.pio/libdeps/featheresp32/ESPRandom_ID6883/examples/get_uuid.cpp.i:
	$(MAKE) -f CMakeFiles/Z_DUMMY_TARGET.dir/build.make CMakeFiles/Z_DUMMY_TARGET.dir/.pio/libdeps/featheresp32/ESPRandom_ID6883/examples/get_uuid.cpp.i
.PHONY : .pio/libdeps/featheresp32/ESPRandom_ID6883/examples/get_uuid.cpp.i

.pio/libdeps/featheresp32/ESPRandom_ID6883/examples/get_uuid.s: .pio/libdeps/featheresp32/ESPRandom_ID6883/examples/get_uuid.cpp.s

.PHONY : .pio/libdeps/featheresp32/ESPRandom_ID6883/examples/get_uuid.s

# target to generate assembly for a file
.pio/libdeps/featheresp32/ESPRandom_ID6883/examples/get_uuid.cpp.s:
	$(MAKE) -f CMakeFiles/Z_DUMMY_TARGET.dir/build.make CMakeFiles/Z_DUMMY_TARGET.dir/.pio/libdeps/featheresp32/ESPRandom_ID6883/examples/get_uuid.cpp.s
.PHONY : .pio/libdeps/featheresp32/ESPRandom_ID6883/examples/get_uuid.cpp.s

src/GUI.obj: src/GUI.cpp.obj

.PHONY : src/GUI.obj

# target to build an object file
src/GUI.cpp.obj:
	$(MAKE) -f CMakeFiles/Z_DUMMY_TARGET.dir/build.make CMakeFiles/Z_DUMMY_TARGET.dir/src/GUI.cpp.obj
.PHONY : src/GUI.cpp.obj

src/GUI.i: src/GUI.cpp.i

.PHONY : src/GUI.i

# target to preprocess a source file
src/GUI.cpp.i:
	$(MAKE) -f CMakeFiles/Z_DUMMY_TARGET.dir/build.make CMakeFiles/Z_DUMMY_TARGET.dir/src/GUI.cpp.i
.PHONY : src/GUI.cpp.i

src/GUI.s: src/GUI.cpp.s

.PHONY : src/GUI.s

# target to generate assembly for a file
src/GUI.cpp.s:
	$(MAKE) -f CMakeFiles/Z_DUMMY_TARGET.dir/build.make CMakeFiles/Z_DUMMY_TARGET.dir/src/GUI.cpp.s
.PHONY : src/GUI.cpp.s

src/main.obj: src/main.cpp.obj

.PHONY : src/main.obj

# target to build an object file
src/main.cpp.obj:
	$(MAKE) -f CMakeFiles/Z_DUMMY_TARGET.dir/build.make CMakeFiles/Z_DUMMY_TARGET.dir/src/main.cpp.obj
.PHONY : src/main.cpp.obj

src/main.i: src/main.cpp.i

.PHONY : src/main.i

# target to preprocess a source file
src/main.cpp.i:
	$(MAKE) -f CMakeFiles/Z_DUMMY_TARGET.dir/build.make CMakeFiles/Z_DUMMY_TARGET.dir/src/main.cpp.i
.PHONY : src/main.cpp.i

src/main.s: src/main.cpp.s

.PHONY : src/main.s

# target to generate assembly for a file
src/main.cpp.s:
	$(MAKE) -f CMakeFiles/Z_DUMMY_TARGET.dir/build.make CMakeFiles/Z_DUMMY_TARGET.dir/src/main.cpp.s
.PHONY : src/main.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... Production"
	@echo "... edit_cache"
	@echo "... Debug"
	@echo "... Z_DUMMY_TARGET"
	@echo "... .pio/libdeps/featheresp32/Adafruit_BusIO_ID6214/Adafruit_BusIO_Register.obj"
	@echo "... .pio/libdeps/featheresp32/Adafruit_BusIO_ID6214/Adafruit_BusIO_Register.i"
	@echo "... .pio/libdeps/featheresp32/Adafruit_BusIO_ID6214/Adafruit_BusIO_Register.s"
	@echo "... .pio/libdeps/featheresp32/Adafruit_BusIO_ID6214/Adafruit_I2CDevice.obj"
	@echo "... .pio/libdeps/featheresp32/Adafruit_BusIO_ID6214/Adafruit_I2CDevice.i"
	@echo "... .pio/libdeps/featheresp32/Adafruit_BusIO_ID6214/Adafruit_I2CDevice.s"
	@echo "... .pio/libdeps/featheresp32/Adafruit_BusIO_ID6214/Adafruit_SPIDevice.obj"
	@echo "... .pio/libdeps/featheresp32/Adafruit_BusIO_ID6214/Adafruit_SPIDevice.i"
	@echo "... .pio/libdeps/featheresp32/Adafruit_BusIO_ID6214/Adafruit_SPIDevice.s"
	@echo "... .pio/libdeps/featheresp32/Adafruit_GFX_Library_ID13/Adafruit_GFX.obj"
	@echo "... .pio/libdeps/featheresp32/Adafruit_GFX_Library_ID13/Adafruit_GFX.i"
	@echo "... .pio/libdeps/featheresp32/Adafruit_GFX_Library_ID13/Adafruit_GFX.s"
	@echo "... .pio/libdeps/featheresp32/Adafruit_GFX_Library_ID13/Adafruit_MonoOLED.obj"
	@echo "... .pio/libdeps/featheresp32/Adafruit_GFX_Library_ID13/Adafruit_MonoOLED.i"
	@echo "... .pio/libdeps/featheresp32/Adafruit_GFX_Library_ID13/Adafruit_MonoOLED.s"
	@echo "... .pio/libdeps/featheresp32/Adafruit_GFX_Library_ID13/Adafruit_SPITFT.obj"
	@echo "... .pio/libdeps/featheresp32/Adafruit_GFX_Library_ID13/Adafruit_SPITFT.i"
	@echo "... .pio/libdeps/featheresp32/Adafruit_GFX_Library_ID13/Adafruit_SPITFT.s"
	@echo "... .pio/libdeps/featheresp32/Adafruit_GFX_Library_ID13/examples/GFXcanvas/GFXcanvasSerialDemo.obj"
	@echo "... .pio/libdeps/featheresp32/Adafruit_GFX_Library_ID13/examples/GFXcanvas/GFXcanvasSerialDemo.i"
	@echo "... .pio/libdeps/featheresp32/Adafruit_GFX_Library_ID13/examples/GFXcanvas/GFXcanvasSerialDemo.s"
	@echo "... .pio/libdeps/featheresp32/Adafruit_GFX_Library_ID13/fontconvert/fontconvert.obj"
	@echo "... .pio/libdeps/featheresp32/Adafruit_GFX_Library_ID13/fontconvert/fontconvert.i"
	@echo "... .pio/libdeps/featheresp32/Adafruit_GFX_Library_ID13/fontconvert/fontconvert.s"
	@echo "... .pio/libdeps/featheresp32/Adafruit_GFX_Library_ID13/glcdfont.obj"
	@echo "... .pio/libdeps/featheresp32/Adafruit_GFX_Library_ID13/glcdfont.i"
	@echo "... .pio/libdeps/featheresp32/Adafruit_GFX_Library_ID13/glcdfont.s"
	@echo "... .pio/libdeps/featheresp32/ESPRandom_ID6883/ESPRandom.obj"
	@echo "... .pio/libdeps/featheresp32/ESPRandom_ID6883/ESPRandom.i"
	@echo "... .pio/libdeps/featheresp32/ESPRandom_ID6883/ESPRandom.s"
	@echo "... .pio/libdeps/featheresp32/ESPRandom_ID6883/examples/get_random_number.obj"
	@echo "... .pio/libdeps/featheresp32/ESPRandom_ID6883/examples/get_random_number.i"
	@echo "... .pio/libdeps/featheresp32/ESPRandom_ID6883/examples/get_random_number.s"
	@echo "... .pio/libdeps/featheresp32/ESPRandom_ID6883/examples/get_uuid.obj"
	@echo "... .pio/libdeps/featheresp32/ESPRandom_ID6883/examples/get_uuid.i"
	@echo "... .pio/libdeps/featheresp32/ESPRandom_ID6883/examples/get_uuid.s"
	@echo "... src/GUI.obj"
	@echo "... src/GUI.i"
	@echo "... src/GUI.s"
	@echo "... src/main.obj"
	@echo "... src/main.i"
	@echo "... src/main.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

